GET http://localhost:5000/users
Authorization: Bearer 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Natasya Desinta",
    "email":"natasyadesinta@gmail.com",
    "password":"123456",
    "confPassword":"123456"
}

###
GET http://localhost:5000/users
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"natasyadesinta@gmail.com",
    "password":"123456"
}